"use strict";
exports.__esModule = true;
var CLIMiniZinc_1 = require("minizinc/build/CLIMiniZinc");
var m = new CLIMiniZinc_1["default"]();
var model = "set of int: Rank = 1..18;\narray[Rank] of int: rankPower =\n   [ 8\n   , 9\n   , 10\n   , 11\n   , 12\n   , 13\n   , 14\n   , 15\n   , 16\n   , 17\n   , 18\n   , 19\n   , 20\n   , 21\n   , 22\n   , 23\n   , 24\n   , 25\n   ];\n \n% Avoid recursive definition between noOfPlayers and rank\n% by defining the inputs in an array of unspecified size.\narray[int] of Rank: playerRanks;\narray[Players] of string: players;\nint: tonjeIndex;\nint: haraldIndex;\nint: clementsIndex;\nint: chickenIndex;\n    \nint: maxPlayersPerTeam = 5;\nint: minPlayersPerTeam = 4;\nint: noOfTeams = ceil(noOfPlayers / maxPlayersPerTeam);\nint: noOfPlayers = length(playerRanks);\nset of int: Players = 1..noOfPlayers;\nset of int: Teams = 1..noOfTeams;\narray[Players] of int: rank = playerRanks;\narray[Players] of var 1..noOfTeams: team; \n\n\n\narray[Teams] of var int: score;\n\nset of int: TeamSize = 4..5;\narray[Teams] of var TeamSize: teamSize;\n\nconstraint forall(t in Teams) (\n     teamSize[t] = sum([team[p] == t | p in Players])\n  );\n\n%  same number of players per team\nconstraint forall(t in Teams) (\n     maxPlayersPerTeam >= sum([team[p] == t | p in Players])\n  );\n\n% Tonje og Harald p\u00E5 samme lag\nconstraint (\n     team[tonjeIndex] == team[haraldIndex]\n  );\n\n    \n%  sum up the ELO numbers per team\nconstraint forall(t in Teams) (\n     score[t] == sum([if team[p] == t then rank[p] else 0 endif | p in Players])\n  );\n  \n%  enforce sorted sums to break symmetries\n%  and avoid minimum/maximum predicates\nconstraint forall(t1 in Teams, t2 in Teams where t1 < t2) (\n    score[t1] <= score[t2]\n  );   \n  \n% Symmetry breaking constraint => last team - first team = greates diff\nsolve minimize score[noOfTeams] - score[1];\noutput outputJSON();";
m.solve({ model: model, solver: "cbc" }, { playerRanks: [6, 3, 16, 11, 16, 16, 13, 13, 12, 12, 3, 1, 8, 10, 8, 4, 7, 8, 4, 1, 6, 7, 13, 1],
    players: ["Darkness  sem 6", "Samuelps  s3. 3", "Chicken lem 16", "Dr.eggman/eask64  mg1.  11", "Ditlesen  lem 16", "wolverin  lem 16", "Crimsonfukrr  mge 13", "Nazario mge 13", "kaptein snabeltann  mg2.  12", "Le pipe mg2.  12", "bna-cooky s3. 3", "ClemensBenz[500E] s1. 1", "Buððah  gn2.  8", "McDuckian gnm 10", "Madde gn2.  8", "Falchy  s4. 4", "KSI gn1.  7", "l0lpalme  gn2.  8", "Youngfafo s4. 4", "antorn3dthe7th  s1. 1", "IQStrom sem 6", "Shabby  gn1.  7", "LuftGraven  mg2.  12", "SchousKanser  s1. 1"],
    tonjeIndex: 15, haraldIndex: 18, chickenIndex: 0, clementsIndex: 0 }).then(function (result) {
    console.log(result);
});
